============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.7.0, py-1.5.2, pluggy-0.7.1 -- /home/travis/virtualenv/python3.6.3/bin/python
cachedir: .pytest_cache
rootdir: /home/travis/build/Fondamenti18/fondamenti-di-programmazione/students/1796936/homework01, inifile:
plugins: timeout-1.3.1, json-0.4.0
timeout: 10.0s
timeout method: signal
timeout func_only: False
collecting ... collected 14 items

grade02.py::Test::test_program_1 PASSED                                  [  7%]
grade02.py::Test::test_program_10 FAILED                                 [ 14%]
grade02.py::Test::test_program_11 FAILED                                 [ 21%]
grade02.py::Test::test_program_12 PASSED                                 [ 28%]
grade02.py::Test::test_program_13 PASSED                                 [ 35%]
grade02.py::Test::test_program_14 FAILED                                 [ 42%]
grade02.py::Test::test_program_2 PASSED                                  [ 50%]
grade02.py::Test::test_program_3 PASSED                                  [ 57%]
grade02.py::Test::test_program_4 PASSED                                  [ 64%]
grade02.py::Test::test_program_5 PASSED                                  [ 71%]
grade02.py::Test::test_program_6 PASSED                                  [ 78%]
grade02.py::Test::test_program_7 PASSED                                  [ 85%]
grade02.py::Test::test_program_8 FAILED                                  [ 92%]
grade02.py::Test::test_program_9 FAILED                                  [100%]

=================================== FAILURES ===================================
_____________________________ Test.test_program_10 _____________________________

self = <grade02.Test testMethod=test_program_10>

    def test_program_10(self):
        'non elisioni 800-1 e elisioni 80-1'
        num      = 801081801081
        expected = 'ottocentounomiliardiottantunomilioniottocentounomilaottantuno'
>       return self.dotest02(num, expected)

grade02.py:76: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
grade02.py:12: in dotest02
    ret  = program.conv(*args)
program02.py:67: in conv
    return conv(n//10**9) + "miliardi" + conv(n%10**9)
program02.py:63: in conv
    return conv(n//10**6) + "milioni" + conv(n%10**6)
program02.py:61: in conv
    return "unmilione" + conv(n%10**6)
program02.py:61: in conv
    return "unmilione" + conv(n%10**6)
E   RecursionError: maximum recursion depth exceeded in comparison
!!! Recursion detected (same locals & position)
_____________________________ Test.test_program_11 _____________________________

self = <grade02.Test testMethod=test_program_11>

    def test_program_11(self):
        'elisioni sessanta-otto, cinquanta-otto, quaranta-otto, trenta-otto'
        num      = 68258148238
        expected = 'sessantottomiliardiduecentocinquantottomilionicentoquarantottomiladuecentotrentotto'
>       return self.dotest02(num, expected)

grade02.py:82: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
grade02.py:12: in dotest02
    ret  = program.conv(*args)
program02.py:67: in conv
    return conv(n//10**9) + "miliardi" + conv(n%10**9)
program02.py:63: in conv
    return conv(n//10**6) + "milioni" + conv(n%10**6)
program02.py:61: in conv
    return "unmilione" + conv(n%10**6)
program02.py:61: in conv
    return "unmilione" + conv(n%10**6)
E   RecursionError: maximum recursion depth exceeded in comparison
!!! Recursion detected (same locals & position)
_____________________________ Test.test_program_14 _____________________________

self = <grade02.Test testMethod=test_program_14>

    def test_program_14(self):
        'numero massimo da convertire'
        num      = 99999999999
        expected = 'novantanovemiliardinovecentonovantanovemilioninovecentonovantanovemilanovecentonovantanove'
>       return self.dotest02(num, expected)

grade02.py:100: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
grade02.py:12: in dotest02
    ret  = program.conv(*args)
program02.py:67: in conv
    return conv(n//10**9) + "miliardi" + conv(n%10**9)
program02.py:63: in conv
    return conv(n//10**6) + "milioni" + conv(n%10**6)
program02.py:61: in conv
    return "unmilione" + conv(n%10**6)
program02.py:61: in conv
    return "unmilione" + conv(n%10**6)
E   RecursionError: maximum recursion depth exceeded in comparison
!!! Recursion detected (same locals & position)
_____________________________ Test.test_program_8 ______________________________

self = <grade02.Test testMethod=test_program_8>

    def test_program_8(self):
        "elisioni 800-80 e 80-8"
        num      = 888888888
        expected = 'ottocentottantottomilioniottocentottantottomilaottocentottantotto'
>       return self.dotest02(num, expected)

grade02.py:64: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
grade02.py:12: in dotest02
    ret  = program.conv(*args)
program02.py:63: in conv
    return conv(n//10**6) + "milioni" + conv(n%10**6)
program02.py:61: in conv
    return "unmilione" + conv(n%10**6)
program02.py:61: in conv
    return "unmilione" + conv(n%10**6)
E   RecursionError: maximum recursion depth exceeded in comparison
!!! Recursion detected (same locals & position)
_____________________________ Test.test_program_9 ______________________________

self = <grade02.Test testMethod=test_program_9>

    def test_program_9(self):
        'non elisioni 800-8 e elisioni 800-80'
        num      = 808080808080
        expected = 'ottocentoottomiliardiottantamilioniottocentoottomilaottanta'
>       return self.dotest02(num, expected)

grade02.py:70: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
grade02.py:12: in dotest02
    ret  = program.conv(*args)
program02.py:67: in conv
    return conv(n//10**9) + "miliardi" + conv(n%10**9)
program02.py:63: in conv
    return conv(n//10**6) + "milioni" + conv(n%10**6)
program02.py:61: in conv
    return "unmilione" + conv(n%10**6)
program02.py:61: in conv
    return "unmilione" + conv(n%10**6)
E   RecursionError: maximum recursion depth exceeded in comparison
!!! Recursion detected (same locals & position)
 generated json report: /home/travis/build/Fondamenti18/fondamenti-di-programmazione/students/1796936/homework01/program02.log.json 
====================== 5 failed, 9 passed in 0.28 seconds ======================
